### ISSUE TITLE
Pre-Project React

### ISSUE THREAD

**Issue by stancsz** [ca-west-1/web-development-project-ensf-607#3]
2020/12/06

What have you done since the last meeting?
read the assignment and introduction, communciated with teammates

What will you do?
read on django tutorials

Did you face any difficulties? Why?
needing a plan to execute the project

**Comment by zchemali** [comment]
- Research on REACT
- Research on API Rest
- Build the React

**Comment by hasnil** [comment]
1. What have you done since the last meeting?
Read assignment and introduction.

2. What will you do?
Acquaint myself with REACT.

3. Did you face any difficulties?
Severe lack of time hampering ability.

**Comment by hasnil** [comment]
1. What have you done since the last meeting?
Watched introductory video and began reading website.

2. What will you do?
Will follow tutorial.

3. Did you face any difficulties?
Being busy with other work remains an obstacle.

**Comment by stancsz** [comment]
2020/12/07

What have you done since the last meeting?
Following a django tutorial 
https://docs.djangoproject.com/en/3.1/ref/
https://www.django-rest-framework.org/tutorial/quickstart/


What will you do?
start a django test

Did you face any difficulties? Why?
being busy with other courses

**Comment by zchemali** [comment]
What have you done since the last meeting?
Read about ES6 JS.

What will you do?
Learn about HTML ,CSS

Did you face any difficulties?
Being busy with other work remains an obstacle.

**Comment by stancsz** [comment]
2020/12/08

What have you done?
googled django

What will you do?
django test in progress

Did you face any difficulties? Why?
django has lots of moving parts

**Comment by stancsz** [comment]
2020/12/09

What have you done?
django test work in progress

What will you do?
finish django test

Did you face any difficulties? Why?
need more time

**Comment by hasnil** [comment]
What have you done since the last meeting?
Installed node js and started rewatching class video.

What will you do?
Work on counter from tutorial video.

Did you face any difficulties?
Trouble learning syntax.

**Comment by zchemali** [comment]
9/12/2020
What have you done since the last meeting?
Reading abut react and how to create the react-app

What will you do?
Start building the counter

Did you face any difficulties? Why?
Was having difficulties building a front end web application from scratch so decided to use the create-react-app instead

**Comment by hasnil** [comment]
December 10, 2020
What have you done since the last meeting?
Implemented preproject React exercise that was shown in lab session.

What will you do?
Continue to learn about React and then begin studying Django.

Did you face any difficulties?
Facing some problems with understanding how different parts of installation work together and how to make connections.
